# Header
menu:
  Home: /
  Documentation: /book
  Archives: /archives
  Forum: /forum/
  About me: /about-me.html
  Man: /man
  sources: https://github.com/pieroproietti/penguins-eggs
  npm: https://www.npmjs.com/package/penguins-eggs
  debs: https://sourceforge.net/projects/penguins-eggs/files/packages-deb/
  ISOs: https://sourceforge.net/projects/penguins-eggs/files/iso/
  facebook: https://www.facebook.com/penguinseggs

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-170278688-1
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: piero.proietti@gmail.com
fb_app_id: 117556782968515
